---
title: "ACDTanguro"
output: html_document
date: "2023-07-30"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tidyterra)
library(terra)
library(lidR)
library(lidRmetrics)
library(sf)
library(Lmoments)
library(ggplot2)

```

```{r}
#functions

#remove extreme values -- mostly the two eddy flux towers. 
filter_noise = function(las, sensitivity)
{
  p99 <- grid_metrics(las, ~quantile(Z, probs = 0.99), 10)
  las <- merge_spatial(las, p99, "p99")
  las <- filter_poi(las, Z < p99*sensitivity)
  las$p99 <- NULL
  return(las)
}

#your function
ACD = function(zmean, zkurt, zq5, zq10, ziqr, zmax) {
  res = (0.20 * zmean^2.02) *(zkurt^0.66)* (zq5^0.11) * (zq10^-0.32) * (ziqr^0.50)*(zmax^-0.82)
  return(res)}

ACD(10, 0.5, 2, 15, 20, 25)
```


```{r}
#shape tanguro plots
##plot_A <- sf::st_read("/Users/pmb75/Dropbox (YSE)/Documents/Manuscript/Tanguro_Synthesis_Fire/data/Shape_Tanguro/Polygon_A_B_C_D.shp")
plot_A <- sf::st_read("C:/Users/xhs4/Dropbox (YSE)/Tanguro_BELA/Tanguro_Synthesis_Fire2/Shape_Tanguro2/Polygon_A_B_C_D.shp")
plot_A <- sf::st_transform(plot_A, crs = 31982)
plot_A <- plot_A %>% 
  mutate(Parcela = ifelse(is.na(Parcela), "D", as.character(Parcela))) %>%
  dplyr::select(Parcela) 

###
###
###
```


```{r}
###
###
###

##path_data <- "/Users/pmb75/Dropbox (YSE)/Documents/Manuscript/Tanguro_Synthesis_Fire/proc_data/LiDAR/Normalized_Clipped_Thinned"
path_data <-"/Users/xhs4/Dropbox (YSE)/Tanguro_BELA/Tanguro_Synthesis_Fire2/proc_data2/LiDAR2/Normalized_Clipped_Thinned2"

###
###
###

#function to estimate ACD
calc_ACD<- function(year, path_data = path_data, res = 25)
  {
  
  #import data
  las_temp <- readLAS(file.path(path_data,
                                paste0("Lidar_normalized_thinned", year, ".las")))

  #remova the noise. 
  las_temp <- filter_noise(las_temp, sensitivity = 1.1)
  
  las_temp <- filter_poi(las_temp, Z<=30)
  #calculate a bunch of metrics you used to paramet. your model
  mm <- grid_metrics(las_temp, ~metrics_set1(Z), res = res)

  #convert from raster to terra format
  m2R <- rast(mm)
  
  #subset for metrics of interest
  sub_las <- m2R[[c("zmean", "zkurt", "zq5", "zq10", "ziqr", "zmax")]]
  
  #estimate ACD for a large area
  lidarACD <- lapp(sub_las, ACD)
  
  return(lidarACD)
  }

```

```{r}

ACD12 <- calc_ACD(2012, path_data = path_data, res = 50)
ACD14 <- calc_ACD(2014, path_data = path_data, res = 50)
ACD18 <- calc_ACD(2018, path_data = path_data, res = 50)
ACD20 <- calc_ACD(2020, path_data = path_data, res = 50)

crop_area <- plot_A |> filter(Parcela != "D")

cCD12 <- crop(ACD12, ACD20)
cCD14 <- crop(ACD14, ACD20)
cCD18 <- crop(ACD18, ACD20)
cCD20 <- crop(ACD20, ACD20)

#fix extent of 2020 files
new_extent <- terra::ext(348050, 350900, 8552850, 8554300)
cCD20_cropped <- crop(ACD20, new_extent)


masterACD <- c(cCD12, cCD14, cCD18, cCD20_cropped)
names(masterACD) <- c("ACD12", "ACD14", "ACD18", "ACD20" )


```

```{r}

ggplot(plot_A|>filter(Parcela != "D")) +
  geom_spatraster(data = masterACD) +
  geom_spatvector(fill = NA) +
  facet_wrap(~lyr) +
  scale_fill_whitebox_c(
    palette = "deep", direction = 1,
    #labels = scales::label_number(suffix = "º"),
    n.breaks = 8
  ) +
  theme_minimal() 


```


```{r}

dACD = c(cCD14-cCD12/2, cCD18-cCD14/2, cCD20_cropped-cCD18/2)
names(dACD) <- c("d14_12", "d18_14", "d20_18")

ggplot(plot_A|>filter(Parcela != "D")) +
  geom_spatraster(data = dACD) +
  geom_spatvector(fill = NA) +
  facet_wrap(~lyr) +
  scale_fill_whitebox_c(
    palette = "deep", direction = 1,
    #labels = scales::label_number(suffix = "º"),
    n.breaks = 8
  ) +
  theme_minimal() 

```

```{r}
#do some stats per plot
PA <- crop(dACD, plot_A |> filter(Parcela == "A"))
PB <- crop(dACD, plot_A |> filter(Parcela == "B"))
PC <- crop(dACD, plot_A |> filter(Parcela == "C"))

###

ggplot() +
  geom_spatraster(data = PA) +
  geom_spatvector(fill = NA) +
  facet_wrap(~lyr) +
  scale_fill_whitebox_c(
    palette = "deep", direction = 1,
    #labels = scales::label_number(suffix = "º"),
    n.breaks = 8
  ) +
  theme_minimal() 
  
#
ggplot() +
  geom_spatraster(data = PB) +
  geom_spatvector(fill = NA) +
  facet_wrap(~lyr) +
  scale_fill_whitebox_c(
    palette = "deep", direction = 1,
    #labels = scales::label_number(suffix = "º"),
    n.breaks = 8
  ) +
  theme_minimal() 
  
#
ggplot() +
  geom_spatraster(data = PC) +
  geom_spatvector(fill = NA) +
  facet_wrap(~lyr) +
  scale_fill_whitebox_c(
    palette = "deep", direction = 1,
    #labels = scales::label_number(suffix = "º"),
    n.breaks = 8
  ) +
  theme_minimal() 

#

m <- merge(PA, PB, PC)

#m2 <- app(m, function(i) ifelse(i > 200, NA, i))
```

```{r}

ggplot(plot_A|>filter(Parcela != "D")) +
  geom_spatraster(data = m) +
  geom_spatvector(fill = NA) +
  facet_wrap(~lyr)+
  scale_fill_whitebox_c(
    palette = "deep", direction = 1,
    #labels = scales::label_number(suffix = "º"),
    n.breaks = 8
  ) +
  theme_minimal() 


```

```{r}
#removing extreme values
#ggplot(plot_A|>filter(Parcela != "D")) +
#  geom_spatraster(data = m2) +
#  geom_spatvector(fill = NA) +
#  scale_fill_whitebox_c(
#    palette = "deep", direction = 1,
#    #labels = scales::label_number(suffix = "º"),
#    n.breaks = 8
#  ) +
#  theme_minimal() 
```

```{r}
library(hrbrthemes)
long_PA <- as.data.frame(PA) |> as_tibble()|>
  pivot_longer(cols = d14_12:d20_18) |> mutate(Period = "Control")
long_PB <- as.data.frame(PB) |> as_tibble()|>
  pivot_longer(cols = d14_12:d20_18)|> mutate(Period = "B3yr")
long_PC <- as.data.frame(PC) |> as_tibble()|>
  pivot_longer(cols = d14_12:d20_18)|> mutate(Period = "B1yr")

long_master <- long_PA |> bind_rows(long_PB) |> bind_rows(long_PC)

long_master |>
  ggplot(aes(x = value, fill = name))+
  geom_histogram( color="#e9ecef", alpha=0.6, position = 'identity') +
    scale_fill_manual(values=c("#69b3a2", "#404080", "orange")) +
    hrbrthemes::theme_ipsum() +
    facet_wrap(~Period) +
    labs(fill="")

global(PA, c("mean", "sum", "max"), na.rm=TRUE)
global(PB, c("mean", "sum", "max"), na.rm=TRUE)
global(PC, c("mean", "sum", "max"), na.rm=TRUE)


```

```{r}
PAdf <- as.data.frame(PA) |> as_tibble()

bmbstats::plot_raincloud(
  data = long_PA,
  value = "value",
  group = "name")

bmbstats::plot_raincloud(
  data = long_PB,
  value = "value",
  group = "name")

bmbstats::plot_raincloud(
  data = long_PC,
  value = "value",
  group = "name")
```


```{r}

bmbstats::plot_raincloud(
  data = long_master |> filter(name == "d14_12"),
  value = "value",
  group = "Period")

bmbstats::plot_raincloud(
  data = long_master |> filter(name == "d18_14"),
  value = "value",
  group = "Period")

bmbstats::plot_raincloud(
  data = long_master |> filter(name == "d20_18"),
  value = "value",
  group = "Period")


```

```{r}

PABtest <- bmbstats::compare_independent_groups(
  group_a = as.data.frame(PA)$d20_18,
  group_b = as.data.frame(PC)$d20_18
)
PABtest
plot(PABtest)

PACtest <- bmbstats::compare_independent_groups(
  group_a = as.data.frame(PA)$d20_18,
  group_b = as.data.frame(PC)$d20_18
)
PACtest
plot(PACtest)

PBCtest <- bmbstats::compare_independent_groups(
  group_a = as.data.frame(PA)$d20_18,
  group_b = as.data.frame(PC)$d20_18
)
PBCtest
plot(PBCtest)



```

```{r}
A_B_NHST <- bmbstats::bootstrap_NHST(
  PABtest,
  estimator = "Mean diff",
  null_hypothesis = 0
)

A_C_NHST <- bmbstats::bootstrap_NHST(
  PACtest,
  estimator = "Mean diff",
  null_hypothesis = 0
)

B_C_NHST <- bmbstats::bootstrap_NHST(
  PBCtest,
  estimator = "Mean diff",
  null_hypothesis = 0
)

plot(A_B_NHST)
plot(A_C_NHST)
plot(B_C_NHST)

```

```{r}

#library(brms)

#m1 <- brm(value ~ Period *name, 
 #         data = long_master, 
  #        chains = 3, cores = 6, backend = "cmdstanr")
#summary(m1)

#library(ggeffects)
#plot(ggpredict(m1, terms = c("Period", "name")))
#plot(ggpredict(m1, terms = c("name", "Period")))

```


